# This is a basic workflow to help you get started with Actions

name: deploy-web

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    types:
      - closed
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command

      - name: Install expo cli
        run: |
          npm install -g expo-cli
          yarn deploy

      # - name: Build the static website and deploy it on gh-pages
      #   uses: Borales/actions-yarn@v2.3.0
      #   with:
      #     cmd: deploy # will run `yarn deploy` command
