name: deploy-web

on:
  pull_request:
    types:
      - closed
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # only build if the pull request was merged (or manually triggered)
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: Install expo cli and build static website
        run: |
          npm install -g expo-cli
          expo build:web

      - name: Deploy on gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          fqdn: myfreetimeinaweek.in
          target_branch: gh-pages
          build_dir: web-build
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
