# This is a basic workflow to help you get started with Actions

name: deploy-web

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    types:
      - closed
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # only build if the pull request was merged
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command

      - name: Install expo cli and build static website
        run: |
          npm install -g expo-cli
          expo build:web

      - name: Deploy on gh-pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          fqdn: myfreetimeinaweek.in
          target_branch: gh-pages
          build_dir: web-build
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
